# Generated by Django 2.1.3 on 2018-11-25 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Career_Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Career')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Professor_Subject_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=10)),
                ('classroom', models.CharField(max_length=30)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Career')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.CharField(blank=True, max_length=30)),
                ('tuesday', models.CharField(blank=True, max_length=30)),
                ('wednesday', models.CharField(blank=True, max_length=30)),
                ('thursday', models.CharField(blank=True, max_length=30)),
                ('friday', models.CharField(blank=True, max_length=30)),
                ('saturday', models.CharField(blank=True, max_length=30)),
                ('sunday', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('hours_per_week', models.IntegerField()),
                ('keycode', models.CharField(max_length=9)),
            ],
        ),
        migrations.AddField(
            model_name='professor_subject_schedule',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Schedule'),
        ),
        migrations.AddField(
            model_name='professor_subject_schedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Subject'),
        ),
        migrations.AddField(
            model_name='career_subject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Subject'),
        ),
        migrations.AlterUniqueTogether(
            name='professor_subject_schedule',
            unique_together={('professor', 'schedule')},
        ),
        migrations.AlterUniqueTogether(
            name='career_subject',
            unique_together={('career', 'subject')},
        ),
    ]
