# Generated by Django 2.1.3 on 2018-11-25 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20181125_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor_subject_schedule',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Professor'),
        ),
    ]
