# Generated by Django 2.1.3 on 2018-11-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20181120_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='hours_per_week',
            field=models.IntegerField(default=0),
        ),
    ]
