# Generated by Django 2.1.3 on 2018-12-06 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_auto_20181125_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career_subject',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='schedules.Career'),
        ),
        migrations.AlterField(
            model_name='career_subject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career', to='schedules.Subject'),
        ),
    ]
